### Numpy
Numpy is a linear algebra library for python

### Creating Numpy Array

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
matrix = [[1,2,4,5], [6,7,16,9]]
matrix

[[1, 2, 4, 5], [6, 7, 16, 9]]

In [5]:
mat = np.array(matrix)
mat.shape

(2, 4)

### Built-in Methods

#### arange

In [6]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
vector = np.arange(0,20,2)
vector

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
vector.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

### Zeros and One
Generate arrays of Zeros and ones

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
matrix_zero = np.zeros((4,4))
matrix_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Linspace
numpy.linspace(start, stop, num=50, endpoint=True, retsep= False, dtype=None, axis=0)

In [13]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [14]:
np.linspace(1,10,)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [15]:
my_linspace = np.linspace(0,10,100)
my_linspace

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [16]:
my_linspace.reshape(20,5)

array([[ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ],
       [ 0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091],
       [ 1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141],
       [ 1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192],
       [ 2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242],
       [ 2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293],
       [ 3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343],
       [ 3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394],
       [ 4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444],
       [ 4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495],
       [ 5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545],
       [ 5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596],
       [ 6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646],
       [ 6.56565657,  6.66666667,  6.7

### Eye
Create an Identity Element

In [17]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

### Random

#### rand
Create an array for a given shape and populate a random sample from a uniform distribution over ``[0,1]``

In [18]:
# Vector
np.random.rand(5)

array([0.20184779, 0.06729813, 0.06304134, 0.56910393, 0.59982368])

In [19]:
# Matrix
np.random.rand(5,5)

array([[6.83542798e-01, 3.07062638e-01, 8.01347659e-01, 9.71556166e-01,
        3.47429107e-02],
       [5.91581443e-01, 8.85697475e-01, 3.44168231e-05, 5.99294907e-01,
        1.99523461e-01],
       [9.25697403e-01, 3.44092683e-02, 8.81046772e-01, 8.31476073e-01,
        2.37506647e-01],
       [3.12124227e-01, 5.20801876e-01, 8.11835274e-01, 3.07515233e-01,
        6.58685507e-01],
       [2.29962520e-01, 8.60357847e-01, 6.79682004e-01, 6.62768248e-01,
        1.94033363e-01]])

#### randn
Return a sample from the "Standard Noormal" distribution. Unlike rand which returns uniform distribution ``-3 to 3``

In [20]:
np.random.randn(2)

array([ 0.46861303, -0.2037422 ])

In [21]:
np.random.randn(3,3)

array([[ 0.34151884,  0.62636908, -0.08808544],
       [-0.8669538 ,  0.47109949, -0.14763002],
       [-0.91282472, -0.83168109, -0.01372585]])

#### randint
Return random integers from ``low`` (inclusive) to ``high`` (exclusive)

In [22]:
np.random.randint(1,100)

45

In [23]:
np.random.randint(1,100,10)

array([30, 95, 99, 65, 65, 23, 80,  5, 72, 20])

#### max, min, argmax, argmin

In [24]:
my_randomInt = np.random.randint(1, 20, 30)
my_randomInt

array([ 7, 13, 10, 12, 17,  5,  1, 12,  7,  8,  5, 15,  3,  5, 19,  5, 19,
       13, 19, 13, 16,  9,  9,  1, 10, 11, 18,  8, 11,  4])

In [25]:
# Returns minimum value in randomInt
my_randomInt.min()

1

In [26]:
# Returnd maximum value in randomInt
my_randomInt.max()

19

In [27]:
# Returns the index(position) of the max value
my_randomInt.argmax()

14

In [28]:
# Returns index of the minimum value
my_randomInt.argmin()

6

#### shape
Return the attributes of an array

In [29]:
my_randomInt.shape

(30,)

#### dtype
Returns the data type of the object

In [30]:
my_linspace.dtype

dtype('float64')

In [31]:
# Calculating exponential
exponent = np.exp(my_linspace)
exponent

array([1.00000000e+00, 1.10628782e+00, 1.22387273e+00, 1.35395549e+00,
       1.49786447e+00, 1.65706921e+00, 1.83319548e+00, 2.02804182e+00,
       2.24359796e+00, 2.48206508e+00, 2.74587836e+00, 3.03773178e+00,
       3.36060565e+00, 3.71779709e+00, 4.11295363e+00, 4.55011049e+00,
       5.03373179e+00, 5.56875615e+00, 6.16064708e+00, 6.81544881e+00,
       7.53984798e+00, 8.34124196e+00, 9.22781435e+00, 1.02086186e+01,
       1.12936704e+01, 1.24940499e+01, 1.38220152e+01, 1.52911270e+01,
       1.69163875e+01, 1.87143934e+01, 2.07035054e+01, 2.29040358e+01,
       2.53384558e+01, 2.80316249e+01, 3.10110451e+01, 3.43071414e+01,
       3.79535725e+01, 4.19875748e+01, 4.64503425e+01, 5.13874480e+01,
       5.68493076e+01, 6.28916963e+01, 6.95763174e+01, 7.69714323e+01,
       8.51525577e+01, 9.42032371e+01, 1.04215893e+02, 1.15292773e+02,
       1.27546990e+02, 1.41103681e+02, 1.56101284e+02, 1.72692948e+02,
       1.91048105e+02, 2.11354190e+02, 2.33818566e+02, 2.58670631e+02,
      

In [32]:
# Calculating log
log = np.log(my_linspace)
log

C:\Users\OMONDI\AppData\Local\Temp\ipykernel_5304\2126815516.py:2: RuntimeWarning: divide by zero encountered in log
  log = np.log(my_linspace)


array([       -inf, -2.29253476, -1.59938758, -1.19392247, -0.9062404 ,
       -0.68309684, -0.50077529, -0.34662461, -0.21309322, -0.09531018,
        0.01005034,  0.10536052,  0.19237189,  0.2724146 ,  0.34652257,
        0.41551544,  0.48005397,  0.54067859,  0.597837  ,  0.65190422,
        0.70319752,  0.75198768,  0.7985077 ,  0.84295946,  0.88551907,
        0.92634107,  0.96556178,  1.00330211,  1.03966975,  1.07476107,
        1.10866262,  1.14145245,  1.17320115,  1.2039728 ,  1.23382577,
        1.2628133 ,  1.29098418,  1.31838316,  1.3450514 ,  1.37102689,
        1.3963447 ,  1.42103731,  1.44513486,  1.46866536,  1.49165488,
        1.51412773,  1.53610664,  1.55761284,  1.57866625,  1.59928554,
        1.61948825,  1.63929088,  1.65870896,  1.67775716,  1.69644929,
        1.71479843,  1.73281693,  1.75051651,  1.76790825,  1.78500269,
        1.80180981,  1.81833911,  1.83459963,  1.85059997,  1.86634833,
        1.88185251,  1.89711998,  1.91215786,  1.92697295,  1.94

In [33]:
# Calculating sin
sin = np.sin(my_linspace)
sin

array([ 0.        ,  0.10083842,  0.20064886,  0.2984138 ,  0.39313661,
        0.48385164,  0.56963411,  0.64960951,  0.72296256,  0.78894546,
        0.84688556,  0.8961922 ,  0.93636273,  0.96698762,  0.98775469,
        0.99845223,  0.99897117,  0.98930624,  0.96955595,  0.93992165,
        0.90070545,  0.85230712,  0.79522006,  0.73002623,  0.65739025,
        0.57805259,  0.49282204,  0.40256749,  0.30820902,  0.21070855,
        0.11106004,  0.01027934, -0.09060615, -0.19056796, -0.28858706,
       -0.38366419, -0.47483011, -0.56115544, -0.64176014, -0.7158225 ,
       -0.7825875 , -0.84137452, -0.89158426, -0.93270486, -0.96431712,
       -0.98609877, -0.99782778, -0.99938456, -0.99075324, -0.97202182,
       -0.94338126, -0.90512352, -0.85763861, -0.80141062, -0.73701276,
       -0.66510151, -0.58640998, -0.50174037, -0.41195583, -0.31797166,
       -0.22074597, -0.12126992, -0.0205576 ,  0.0803643 ,  0.18046693,
        0.27872982,  0.37415123,  0.46575841,  0.55261747,  0.63

In [34]:
# Returns determinant of matrix

matrix2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

np.linalg.det(matrix2)

-9.51619735392994e-16

In [35]:
# Return Diagonal elements
matrix2.diagonal()

array([1, 5, 9])

#### Retun trace

The trace of a matrix is the sum of the diagonal elements and is often used under the hood in machine learning methods. Given a Numpy Multidimensional array, we can calculate the trace using the trace. We can also return the diagonal of a matrix and calculate its sum:

In [36]:
matrix2.trace()

15

### Discussion
Eigenvectors are widely used in machine learning libraries. Intuitively, given a linear transformation represented by a matrix, A, eigenvectors are vvectors that, when that transmission is applied, change only in scale(not direction). More formally:

Av = λv

where A is a square matrix, λ contains the eigenvalues and v contains the eigenvectors. In Numpy's linear algebra toolset, eig let us calculate the eigenvalues, and eigenvectors of any square matrix.

In [37]:
# Calculate eigenvalues and eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(matrix2)

np.linalg.eig(matrix2)

(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [38]:
# Calculate  the dot product
# Create two vectors

vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.dot(vector_a, vector_b)

32